### ISSUE TITLE
Hello~~~,i just want photos converter to GIF or MP4 ，how to fimplify the ./congifure

### ISSUE THREAD

**Issue by o0o0oo00** [DarkTussin/SimplifyFFMPEG#1]

**Comment by TyraelElDruin** [comment]
https://unix.stackexchange.com/questions/40638/how-to-do-i-convert-an-animated-gif-to-an-mp4-or-mv4-on-the-command-line

**Comment by TyraelElDruin** [comment]
I misread your question http://hamelot.io/visualization/using-ffmpeg-to-convert-a-set-of-images-into-a-video/

**Comment by TyraelElDruin** [comment]
I'm not sure this program will work for your use case

**Comment by TyraelElDruin** [comment]
More https://stackoverflow.com/questions/24961127/how-to-create-a-video-from-images-with-ffmpeg
